# The Docker image that will be used to build your app
pages:
  script:
    - mkdir -p public
    - rsync -av --exclude=public ./ public
  artifacts:
      paths:
       - public
  only:
    - main     
